version: "3.9"
services:
  mininet:
    image: "opennetworking/mn-stratum"
    privileged: true
    tty: true
    environment:
      - DISPLAY
    volumes:
      - /tmp/mn-stratum:/tmp
    depends_on:
      - "odl"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
    command:
      - bash -c "echo enomine"
#      - mn --controller=remote,ip=10.5.0.6,port=6653 --mac --switch=ovsk,protocols=OpenFlow13 --topo=single,3
  odl:
    image: "rubenqc/odl"
    tty: true
    ports:
      - "8181:8181"
      - "6653:6653"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
networks:
  vpcbr:
    driver: bridgedco
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
