version: "3.9"
services:
  mininet:
    build:
      context: .
    image: rubenqc/mininet
    stdin_open: true
    tty: true
    network_mode: "bridge"
    privileged: true
    environment:
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /lib/modules:/lib/modules
      - ./init_mininet.sh:/ENTRYPOINT.sh
    depends_on:
      - "odl"
  odl:
    image: "rubenqc/odl"
    tty: true
    ports:
      - "8181:8181"
    network_mode: "bridge"
